### PR TITLE
reattach old history for easier spelunking of where code came from

### PR DESCRIPTION
**Pull request by wchristian**
I'd like to reattach the old history to the work made here, and if you agree to do that, there are two options here:

1. do a fast-forward merge of this branch, master_old_merge. As you can see in the "Files changed" tab above, it is identical with master. All it does is add the history that came before this repo was started.
2. do it without any merge, fetch `master_old`, hard reset `master` onto `master_old`, then force push that onto master. Given how young this project is i think that would be an acceptable step to take.

### CODE REVIEW

**Comment by devel-chm** [comment]
The whole point of this is to make a stand alone GLUT/FreeGLUT
module which is extractedfrom OpenGL for back compatibility
rather than making a clean start.

I propose editing the original commit message with a description
of where the implementation comes from and the URL for the
OpenGL git repository.

There is still more cleanup coming to remove code that is
not needed for GLUT/FreeGLUT bindings.  As things are
streamlined further, the old git log will be even less relevant.

Thanks,
Chris

**Comment by wchristian** [comment]
> original commit message

The message of which commit?

**Comment by devel-chm** [comment]
The first commit, a79b846937f0eccbe47ee0782aeac323f506c42f

**Comment by wchristian** [comment]
Maybe I'm missing something, but I'm not aware of any way to usefully modify that one without rebasing and force pushing all commits. Then again, as young as this is that my be fine?

Also, serious question, what is the cost for you in simply having all the history there as opposed to having a message that says "go there and diff it manually"? I honestly just don't understand why you'd impose that cost on another when i can't see a cost for you in the Alternative.

**Comment by devel-chm** [comment]
I think you're right.  Editing the commit message(s) doesn't make sense.  Since this is the first release of the split off bindings, the information can go in  the Changes and README.md.

> Also, serious question, what is the cost for you in simply having all the history there as opposed to having a message that says "go there and diff it manually"? I honestly just don't understand why you'd impose that cost on another when i can't see a cost for you in the Alternative.

I'm not imposing any cost on another user.  They can go to the OpenGL repo and find all the gory history they want.

The cost I don't want to impose is having a huge repository with changes against removed and now external code and functionality which still exists and is still usable and editable and against which further development can be made.  The current OpenGL::GLUT is meant as a way for legacy OpenGL users to continue with their existing code while being able to transition to OpenGL::Modern.

Personally, I don't plan on continued development with OpenGL::GLUT.  That effort will go into developing of OpenGL::GLFW and other modules (see the wiki for OpenGL::Modern for discussion and more context).

**Comment by wchristian** [comment]
I can understand your point of view, but given that the size of the cost you consider is considerably less than what you see, my point of view doesn't seem sufficiently clear yet. I don't think trying to explain it further though would be appreciated, so i'll close this here and just let the merge exist in my fork of the repo: https://github.com/wchristian/OpenGL-GLUT/tree/master_old_merge

You could point people at that in the readme.

**Comment by devel-chm** [comment]
What about making an OpenGL-GLUT branch on the sf.net git repo with the
history there?  All in one nice place and you could indicate that the CPAN
version repo is on github.

**Comment by wchristian** [comment]
I'm operating under the assumption this one will be the canonical repo.

As such, i'd rather keep the fork with the history on github so people who know to look at https://github.com/devel-chm/OpenGL-GLUT/network can find it easier.

I don't understand what practical advantage having that fork on SF would have for anyone.

**Comment by devel-chm** [comment]
The point is that all the history only really makes sense in the context of OpenGL.  If you want to have a fork of that repo on github to refer to that makes more sense to me than keeping the development history of OpenGL and adding it to the OpenGL::GLUT repo.  While the files in OpenGL::GLUT did originate from OpenGL, there have been wholesale deletions and edits of now unneeded functionality with deletions.

The result is that the OpenGL git history only makes sense in context of OpenGL and its files.  I think the only people who would understand that context in OpenGL::GLUT would have to go back to OpenGL 0.70 context from which OpenGL::GLUT was carved.

I appreciate that you feel preserving the history is important and it is.  I differ in where I think it would be most useful---historically and going forward with the new software engineering.  I prefer that it not clutter up OpenGL::GLUT since part of the process is to simplify and clarify the OpenGL API support in perl going forwards.

Mixing in the description of the full history of OpenGL is likely to confuse newcomers.  I think it would be clear to git historians how to access OpenGL repo if they need to do some software archeology.

**Comment by wchristian** [comment]
I hope you won't take this badly, but this is how it is for me: I disagree with not all but many of your assumptions, but in the face of stakes this low, and confidence on your end being so high, have no desire to spend much time on discussing it. That said:

I already committed to keeping this repo pristine by removing the branch from it.

I will keep my history-preserving copy alive in my own fork and am not particularly concerned about it beyond that. You seem to not have any specific desire to see it on SF, so:

All's good, right?

**Comment by devel-chm** [comment]
I would like to document the repo for OpenGL::GLUT.
What is the relevant URL/repo info?

Thanks,
Chris

**Comment by wchristian** [comment]
This'll be enough to have people find it: https://github.com/wchristian/OpenGL-GLUT

They can just add the ssh or https url from there as a remote and do a fetch to get the history.

**Comment by devel-chm** [comment]
Christian-

I've reconsidered.  While there are some advantages for keeping the log
simple, it seems like it is also discounting all the contributions and
efforts that made it possible.  Would you mind re-opening this and apply
it to OpenGL-GLUT?  I think option 2 is fine given that we haven't
had an official release yet.

Regards,
Chris

**Comment by wchristian** [comment]
No problem, will get it done in a few minutes. :)

**Comment by wchristian** [comment]
Force-push done. You'll need to do:

- git fetch
- git checkout master
- git diff master..origin/master
- git reset --hard origin/master

**Comment by devel-chm** [comment]
Thanks.  I think with some pod and Changes we will be ready for the
official release.
Folks can use the CHM/OpenGL-GLUT-0.70_01.tar.gz in the meantime for
verification...

**Pull request closed without merging**
